#ifndef HARDWARE_DP32G030_TIMERBASE_H
#define HARDWARE_DP32G030_TIMERBASE_H

#if !defined(__ASSEMBLY__)
#include <stdint.h>
#endif

#define TIMER_BASE0_BASE_ADDR 0x40064000U

#define TIMER_BASE0_EN_ADDR        (TIMER_BASE0_BASE_ADDR + 0x00U)
#define TIMER_BASE0_EN             (*(volatile uint32_t *)TIMER_BASE0_EN_ADDR)
#define TIMER_BASE0_DIV_ADDR       (TIMER_BASE0_BASE_ADDR + 0x04U)
#define TIMER_BASE0_DIV            (*(volatile uint32_t *)TIMER_BASE0_DIV_ADDR)
#define TIMER_BASE0_IE_ADDR        (TIMER_BASE0_BASE_ADDR + 0x10U)
#define TIMER_BASE0_IE             (*(volatile uint32_t *)TIMER_BASE0_IE_ADDR)
#define TIMER_BASE0_IF_ADDR        (TIMER_BASE0_BASE_ADDR + 0x14U)
#define TIMER_BASE0_IF             (*(volatile uint32_t *)TIMER_BASE0_IF_ADDR)
#define TIMER_BASE0_HIGH_LOAD_ADDR (TIMER_BASE0_BASE_ADDR + 0x20U)
#define TIMER_BASE0_HIGH_LOAD      (*(volatile uint32_t *)TIMER_BASE0_HIGH_LOAD_ADDR)
#define TIMER_BASE0_HIGH_CNT_ADDR  (TIMER_BASE0_BASE_ADDR + 0x24U)
#define TIMER_BASE0_HIGH_CNT       (*(volatile uint32_t *)TIMER_BASE0_HIGH_CNT_ADDR)
#define TIMER_BASE0_LOW_LOAD_ADDR  (TIMER_BASE0_BASE_ADDR + 0x30U)
#define TIMER_BASE0_LOW_LOAD       (*(volatile uint32_t *)TIMER_BASE0_LOW_LOAD_ADDR)
#define TIMER_BASE0_LOW_CNT_ADDR   (TIMER_BASE0_BASE_ADDR + 0x34U)
#define TIMER_BASE0_LOW_CNT        (*(volatile uint32_t *)TIMER_BASE0_LOW_CNT_ADDR)

#define TIMER_BASE_EN_LOW_SHIFT  0
#define TIMER_BASE_EN_HIGH_SHIFT 1
#define TIMER_BASE_EN_LOW        (1u << TIMER_BASE_EN_LOW_SHIFT)
#define TIMER_BASE_EN_HIGH       (1u << TIMER_BASE_EN_HIGH_SHIFT)

#define TIMER_BASE_IE_LOW_SHIFT  0
#define TIMER_BASE_IE_HIGH_SHIFT 1
#define TIMER_BASE_IE_LOW        (1u << TIMER_BASE_IE_LOW_SHIFT)
#define TIMER_BASE_IE_HIGH       (1u << TIMER_BASE_IE_HIGH_SHIFT)

#define TIMER_BASE_IF_LOW_SHIFT  0
#define TIMER_BASE_IF_HIGH_SHIFT 1
#define TIMER_BASE_IF_LOW        (1u << TIMER_BASE_IF_LOW_SHIFT)
#define TIMER_BASE_IF_HIGH       (1u << TIMER_BASE_IF_HIGH_SHIFT)

#endif
